# Please visit https://coveralls.io/refresh , find the repo and flick it on.
# When the repo is ready, you should see a button labeled “Details” on it.
# Click it and paste the line `repo_token: …` into this file. Feel free
# to remove this comment afterwards.
