#! /usr/bin/env node

const commanderToMarkdown = require('commander-to-markdown');
const fs = require('fs');

[{
  bin: 'monopod',
  target: 'Readme.md',
  logicModule: '..',
}, {
  bin: 'monopod-bootstrap',
  target: 'Readme/bootstrap.md',
  logicModule: '../bootstrap',
}].forEach((params) => {
  const bin = params.bin;
  const target = params.target;
  const logicModule = params.logicModule;

  const options = commanderToMarkdown(
    `${__dirname}/../bin/${bin}`, { programModules: [logicModule] }
  );

  const readmePath =
    `${__dirname}/../${target}`;
  const currentReadme =
    fs.readFileSync(readmePath, 'utf8');
  const newReadme =
    currentReadme.replace(
      /(<!-- @options start -->)[^]*(<!-- @options end -->)/,
      `$1\n${options}$2`
    );

  fs.writeFileSync(readmePath, newReadme);
});
